export const userRoles = {
    customer: 'Customer',
    operator: 'Operator',
    admin: 'Admin',
    superAdmin: 'SuperAdmin'
};

export const APIConfig = {
    EXCHANGETYPE: 'ExchangeType',
    BEARINGBRAND: 'BearingBrand',
    BEARINGMODEL: 'BearingModel',
    REASONTYPE: 'ReasonType',
    POSITIONTYPE: 'ShaftPosition',
    BEARINGTYPE: 'BearingType',
    GENERATORMODEL: 'GeneratorModel',
    STATE: 'State',
    CUSTOMERWINDFARM: 'CustomerWindFarm',
    CUSTOMERWINDLOCATION: 'CustomerWindLocation',
    LUBRICATIONTYPE: 'LubricationType',
    LUBRICATIONGRADE: 'LubricationGrade'
}

export const KEYMapper = {
   ID: 'Id',
   REMOVEDBEARINGBRAND: 'RemovedBearingBrand',
   REMOVEDBEARINGTYPE : 'RemovedBearingType',
   NEWBEARINGBRAND: 'NewBearingBrand',
   NEWBEARINGTYPE: 'NewBearingType',
   POSITION: 'ShaftPosition',
   REASONS: 'ReasonType',
   EXCHANGETYPE: 'ExchangeType',
   OPERATORID: 'OperatorId',
   CUSTOMERID: 'CustomerId',
   CUSTOMER: 'Customer',
   WINDTURBINE: 'WindTurbine',
   DATAMATRIX: 'DataMatrix',
   BATCHNUMBER: 'BatchNumber',
   IRNUMBER: 'IRNumber',
   ORNUMBER: 'ORNumber',
   COMMENTS: 'Comments',
   WINDFARM: 'CustomerWindFarm',
   JOBID: 'JobId',
   JOBDATE: 'JobDate',
   OPERATORNAME: 'OperatorName',
   CUSTOMERNAME: 'CustomerName',
   GENERATORMODEL: 'GeneratorModel',
   COMMENTS: 'Comments',
   BEARINGMODEL: 'BearingModel',
   STATE: 'State',
   FAILUREDATE: 'FailureDate',
   WINDLOCATION: 'CustomerWindLocation',
   SERIALNUMBER: 'SerialNumber',
   NOKBEARING: 'NOKBearing',
   SHAFTNDEMAX: 'ShaftJournalNDEMax',
   SHAFTNDEMIN: 'ShaftJournalNDEMin',
   BEARINGNDEMAX: 'BearingHousingNDEMax',
   BEARINGNDEMIN: 'BearingHousingNDEMin',
   SHAFTDEMAX: 'SharftJournalDEMax',
   SHAFTDEMIN: 'ShaftJournalDEMin',
   BEARINGDEMAX: 'BearingHousingDEMax',
   BEARINGDEMIN: 'BearingHousingDEMin',
   LASTLUBRICATION: 'LastLubrication',
   INSULATERESISTANCE: 'InsulateResistance',
   VOLTAGETESTED: 'VoltageTested',
   REPORTDATE: 'ReportDate',
   LUBRICATIONTYPE: 'LubricationType',
   REPORTID: 'ReportId',
   LUBRICATIONGRADE: 'LubricationGrade',
   NAME: 'Name'
};
