export const userRoles = {
    customer: 'Customer',
    operator: 'Operator',
    admin: 'Admin',
    superAdmin: 'SuperAdmin'
};

export const APIConfig = {
    EXCHANGETYPE: 'ExchangeType',
    BEARINGBRAND: 'BearingBrand',
    BEARINGMODEL: 'BearingModel',
    REASONTYPE: 'ReasonType',
    POSITIONTYPE: 'ShaftPosition',
    BEARINGTYPE: 'BearingType',
    GENERATORMODEL: 'GeneratorModel',
    STATE: 'State',
    CUSTOMERWINDFARM: 'CustomerWindFarm',
    CUSTOMERWINDLOCATION: 'CustomerWindLocation',
    LUBRICATIONTYPE: 'LubricationType',
    LUBRICATIONGRADE: 'LubricationGrade',
    COUNTRY: 'Country',
    CUSTOMERSECTOR: 'CustomerSector'
}

export const KEYMapper = {


"BATCHNUMBER": "BatchNumber", 
"BEARINGDEMAX": "BearingHousingDEMax", 
"BEARINGDEMIN": "BearingHousingDEMin", 
"BEARINGMODEL": "BearingModel", 
"BEARINGNDEMAX": "BearingHousingNDEMax",
 "BEARINGNDEMIN": "BearingHousingNDEMin", 
 "COMMENTS": "Comments", 
 "COMPANY": "Company", 
 "COUNTRY": "Country", 
 "CUSTOMER": "Customer",
 "CUSTOMERID": "CustomerId", 
 "CUSTOMERNAME": "CustomerName", 
 "CUSTOMERWINDFARM": "CustomerWindFarm", 
 "DATAMATRIX": "DataMatrix", 
 "DEBATCHNUMBER": "DEBatchNumber", 
 "DEDATAMATRIX": "DEDataMatrix", 
 "EMAIL": "Email", 
 "EXCHANGETYPE": "ExchangeType", 
 "FAILUREDATE": "FailureDate", 
 "GENERATORMODEL": "GeneratorModel", 
 "ID": "Id",
 "INSULATERESISTANCE": "InsulateResistance",
 "IRNUMBER": "IRNumber", 
 "JOBDATE": "JobDate", 
 "JOBID": "JobId", 
 "LASTLUBRICATION": "LastLubrication", 
 "LUBRICATIONGRADE": "LubricationGrade", 
 "LUBRICATIONTYPE": "LubricationType", 
 "NAME": "Name", 
 "NDEBATCHNUMBER": "NDEBatchNumber", 
 "NDEDATAMATRIX": "NDEDataMatrix", 
 "NEWBEARINGBRAND": "NewBearingBrand", "NEWBEARINGTYPE": "NewBearingType", 
 "NOKBEARING": "NOKBearing", "OPERATORID": "OperatorId", "OPERATORNAME": "OperatorName",
  "ORNUMBER": "ORNumber", "POSITION": "ShaftPosition", "REASONS": "ReasonType",
   "REMOVEDBEARINGBRAND": "RemovedBearingBrand",
    "REMOVEDBEARINGTYPE": "RemovedBearingType", "REMOVEDDEBATCHNUMBER": "RemovedDEBatchNumber",
     "REMOVEDDEDATAMATRIX": "RemovedDEDataMatrix", "REMOVEDNDEBATCHNUMBER": "RemovedNDEBatchNumber", 
     "REMOVEDNDEDATAMATRIX": "RemovedNDEDataMatrix", "REPORTDATE": "ReportDate",
      "REPORTID": "ReportId", "SECTOR": "Sector", "SENSORDEBATCHNUMBER": "SensorDEBatchNumber",
       "SENSORDEDATAMATRIX": "SensorDEDataMatrix", "SENSORNDEBATCHNUMBER": "SensorNDEBatchNumber", 
       "SENSORNDEDATAMATRIX": "SensorNDEDataMatrix", "SERIALNUMBER": "SerialNumber",
        "SHAFTDEMAX": "ShaftJournalDEMax", "SHAFTDEMIN": "ShaftJournalDEMin", 
        "SHAFTNDEMAX": "ShaftJournalNDEMax", "SHAFTNDEMIN": "ShaftJournalNDEMin",
         "STATE": "State", "VOLTAGETESTED": "VoltageTested", "WINDFARM": "CustomerWindFarm", 
        "WINDLOCATION": "CustomerWindLocation", "WINDTURBINE": "WindTurbine",





//    ID: 'Id',
//    REMOVEDBEARINGBRAND: 'RemovedBearingBrand',
//    REMOVEDBEARINGTYPE : 'RemovedBearingType',
//    NEWBEARINGBRAND: 'NewBearingBrand',
//    NEWBEARINGTYPE: 'NewBearingType',
//    POSITION: 'ShaftPosition',
//    REASONS: 'ReasonType',
//    EXCHANGETYPE: 'ExchangeType',
//    OPERATORID: 'OperatorId',
//    CUSTOMERID: 'CustomerId',
//    CUSTOMER: 'Customer',
//    WINDTURBINE: 'WindTurbine',
//    DATAMATRIX: 'DataMatrix',
//    BATCHNUMBER: 'BatchNumber',
//    IRNUMBER: 'IRNumber',
//    ORNUMBER: 'ORNumber',
//    COMMENTS: 'Comments',
//    CUSTOMERWINDFARM: 'CustomerWindFarm',
//    JOBID: 'JobId',
//    JOBDATE: 'JobDate',
//    OPERATORNAME: 'OperatorName',
//    CUSTOMERNAME: 'CustomerName',
//    GENERATORMODEL: 'GeneratorModel',
//    COMMENTS: 'Comments',
//    BEARINGMODEL: 'BearingModel',
//    STATE: 'State',
//    FAILUREDATE: 'FailureDate',
//    WINDLOCATION: 'CustomerWindLocation',
//    SERIALNUMBER: 'SerialNumber',
//    NOKBEARING: 'NOKBearing',
//    SHAFTNDEMAX: 'ShaftJournalNDEMax',
//    SHAFTNDEMIN: 'ShaftJournalNDEMin',
//    BEARINGNDEMAX: 'BearingHousingNDEMax',
//    BEARINGNDEMIN: 'BearingHousingNDEMin',
//    SHAFTDEMAX: 'ShaftJournalDEMax',
//    SHAFTDEMIN: 'ShaftJournalDEMin',
//    BEARINGDEMAX: 'BearingHousingDEMax',
//    BEARINGDEMIN: 'BearingHousingDEMin',
//    LASTLUBRICATION: 'LastLubrication',
//    INSULATERESISTANCE: 'InsulateResistance',
//    VOLTAGETESTED: 'VoltageTested',
//    REPORTDATE: 'ReportDate',
//    LUBRICATIONTYPE: 'LubricationType',
//    REPORTID: 'ReportId',
//    LUBRICATIONGRADE: 'LubricationGrade',
//    NAME: 'Name',
//    NDEDATAMATRIX: 'NDEDataMatrix',
//    DEDATAMATRIX: 'DEDataMatrix',
//    SENSORDEDATAMATRIX : 'SensorDEDataMatrix',
//    SENSORNDEDATAMATRIX : 'SensorNDEDataMatrix',
//    REMOVEDDEDATAMATRIX: 'RemovedDEDataMatrix',
//    DEBATCHNUMBER: 'DEBatchNumber',
//    NDEBATCHNUMBER: 'NDEBatchNumber',
//    SENSORDEBATCHNUMBER: 'SensorDEBatchNumber',
//    SENSORNDEBATCHNUMBER: 'SensorNDEBatchNumber',
//    REMOVEDDEBATCHNUMBER: 'RemovedDEBatchNumber',
//    REMOVEDNDEDATAMATRIX: 'RemovedNDEDataMatrix',
//    REMOVEDNDEBATCHNUMBER: 'RemovedNDEBatchNumber',


};
