export const GET_SIGNED_USER = 'GET_SIGNED_USER';
export const ADD_SIGNED_USER_DATA = 'ADD_SIGNED_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_JOBS = 'GET_JOBS';
export const GET_SEARCH_JOBS = 'GET_SEARCH_JOBS';
export const DELETE_jOB_ITEM = 'DELETE_jOB_ITEM';
export const ADD_JOB_ITEM = 'ADD_JOB_ITEM';
export const SELECTED_JOB_ID = 'SELECTED_JOB_ID';
export const UPDATE_JOB_ITEM = 'UPDATE_JOB_ITEM';
export const LOADING_jOBS = 'LOADING_jOBS';
export const SHOW_BARCODE_BUTTON = 'SHOW_BARCODE_BUTTON';
export const SET_JOB_TITLE = 'SET_JOB_TITLE';

export const GET_REPORTS = 'GET_REPORTS';
export const DELETE_REPORT_ITEM = 'DELETE_REPORT_ITEM';
export const ADD_REPORT_ITEM = 'ADD_REPORT_ITEM';


export const GET_ATTACHMENTS = 'GET_ATTACHMENTS';
export const DELETE_ATTACHMENT_ITEM = 'DELETE_ATTACHMENT_ITEM';
export const ADD_ATTACHMENT_ITEM = 'ADD_ATTACHMENT_ITEM';

export const GET_EXCHANGE_TYPES = 'GET_EXCHANGE_TYPES';
export const GET_SHAFT_POSITIONS = 'GET_SHAFT_POSITIONS';
export const GET_REASON_OF_CHANGES = 'GET_REASON_OF_CHANGES';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_MODELS = 'GET_MODELS';
export const GET_BEARING_TYPES = 'GET_BEARING_TYPES';
export const GET_GENERATOR_MODELS = 'GET_GENERATOR_MODELS';
export const GET_WIND_FARMS = 'GET_WIND_FARM';
export const GET_WIND_LOCATIONS = 'GET_WIND_LOCATIONS';
export const GET_STATES = 'GET_STATES';
export const GET_OPERATORS = 'GET_OPERATORS';

export const GET_API_Mapper = 'GET_API_Mapper';
export const GET_KEY_Mapper = 'GET_KEY_Mapper';